#!/usr/bin/env python3
"""Compute text-statistical features on every PR spec.

No LLM calls — pure text analysis. One pass, comprehensive feature set.
Outputs data/pr-features.csv with one row per PR.

Features are organized into categories:
1. AUTHOR CLASSIFICATION — is the author a bot/AI agent?
2. AI SELF-TAGS — does the text declare itself AI-generated?
3. HUMANNESS SIGNALS — typos, casual language, questions, uncertainty
4. ORGANIZATIONAL CONTEXT — references only a human could make
5. REASONING QUALITY — negation depth, causal chains, tradeoffs
6. TEMPLATE/SLOP — performative structure without substance
7. TEXT STATISTICS — burstiness, vocabulary diversity, word length

Usage:
    python3 compute-features.py
"""

import csv
import json
import re
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"

# ═══════════════════════════════════════════════════════════════════════
# 1. AUTHOR CLASSIFICATION
# ═══════════════════════════════════════════════════════════════════════

BOT_AUTHORS = {
    # CI/release bots
    'robobun', 'denobot', 'nextjs-bot', 'vercel-release-bot', 'ti-chi-bot',
    'dotnet-bot',
    # Automation (dependency bumps, releases — not development)
    'renovate', 'dependabot', 'github-actions', 'clerk-cookie',
    'greenkeeper', 'snyk', 'mergify', 'codecov',
    'mendral-app', 'n8n-assistant', 'promptfoobot',
    'scheduled-actions', 'grafana-pr-automation', 'grafana-delivery-bot',
    'langchain-model-profile-bot',
    # Project-specific bots (identified by substring matching in analysis)
    'vitess-bot', 'pwshbot', 'k8s-infra-cherrypick-robot',
    'medplumbot', 'refine-bot', 'lobehubbot', 'qdrant-cloud-bot',
    # Autonomous AI coding agents (agent-authored, not human-using-AI)
    'copilot-swe-agent', 'devin-ai-integration', 'cursor',
}

# ═══════════════════════════════════════════════════════════════════════
# 2. AI SELF-TAGS (ground truth)
# ═══════════════════════════════════════════════════════════════════════

AI_TAG_RE = re.compile(
    r'(?:Generated with|Claude Code|written (?:with|by) (?:claude|codex|copilot|cursor|devin)|'
    r'🤖|CURSOR_AGENT|coderabbit\.ai|auto-generated comment|'
    r'Generated by|AI-generated|Authored by .+(?:AI|agent|bot))',
    re.IGNORECASE,
)

# Structured AI Disclosure section (used by some repos as a PR template field)
# Matches both "AI Disclosure" and "AI Usage" section headers
AI_DISCLOSURE_RE = re.compile(
    r'(?:##\s*)?(?:AI Disclosure|AI Usage)[:\s#]*\n+(.*?)(?:\n\n|\n##|\Z)',
    re.IGNORECASE | re.DOTALL,
)
# Patterns that indicate "no AI used" in a disclosure section
AI_DISCLOSURE_NEGATIVE_RE = re.compile(
    r'(?:no ai|not used|none|n/a|no,\s|nope|no usage)',
    re.IGNORECASE,
)
# Patterns that indicate "AI was used" in a disclosure section
AI_DISCLOSURE_POSITIVE_RE = re.compile(
    r'(?:ai (?:was )?used|ai assist|cursor|copilot|claude|chatgpt|gpt-[45]|gpt[45]|'
    r'openai|gemini|ai tool|ai.generated|used ai|with ai|ai help|'
    r'implemented using|authored by devin|created by devin|'
    r'antigravity|codex|openclaw|opencode)',
    re.IGNORECASE,
)


def _check_ai_disclosure(body: str) -> bool | None:
    """Parse structured AI Disclosure sections in PR body.

    Returns True if disclosure says AI was used, False if it says no AI,
    None if no disclosure section found or content is ambiguous/template.
    """
    m = AI_DISCLOSURE_RE.search(body)
    if not m:
        return None
    val = m.group(1).strip()
    if not val or val.startswith('<!--'):
        return None  # Template placeholder, not filled in
    if AI_DISCLOSURE_NEGATIVE_RE.search(val):
        return False
    if AI_DISCLOSURE_POSITIVE_RE.search(val):
        return True
    return None  # Ambiguous

# ═══════════════════════════════════════════════════════════════════════
# 3. HUMANNESS SIGNALS
# ═══════════════════════════════════════════════════════════════════════

# Typos — robots don't misspell (5x signal)
TYPO_RE = re.compile(
    r'\b(?:teh|taht|waht|hte|becuase|becasue|beacuse|wiht|adn|recieve|occured|'
    r'occurence|seperator|seperate|definately|accomodate|thier|accidently|'
    r'unfortunatly|unfortuantely|wierd|doesnt|dont|cant|wont|isnt|hasnt|'
    r'havent|shouldnt|wouldnt|didnt|ive |im |itll|thats|whats|heres|theres|'
    r'wanna|gonna|gotta|kinda|sorta)\b',
    re.IGNORECASE,
)

# Casual/informal — robots don't use slang (2x signal)
CASUAL_RE = re.compile(
    r'\b(?:hmm|hm|ugh|oops|whoops|argh|yep|nope|yup|nah|btw|fwiw|imo|imho|'
    r'afaik|afaict|tbh|lol|lgtm|wip|nit:|nit |FYI|TIL |IIRC|OTOH|FWIW)\b',
    re.IGNORECASE,
)

# Questions — strongest human signal (16x). AI almost never admits uncertainty.
QUESTION_RE = re.compile(
    r'(?:should we|open question|do we need|not sure (?:if|whether)|TBD|'
    r'to be determined|thoughts\?|feedback\?|what do you think|'
    r'wondering if|is this the right|does this make sense|any concerns|'
    r'am I missing|could this cause|would it be better)',
    re.IGNORECASE,
)

# First person EXPERIENCE narration — "I ran into", "I noticed"
# (Note: AI mimics this at higher rates! Must be combined with other signals)
FIRST_PERSON_EXP_RE = re.compile(
    r'\b(?:I ran into|I found that|I noticed|I tried|I checked|I was|'
    r'I had to|I got|I debugged|I looked into|I realized|I.m not sure|'
    r'I understand|I suspect|I think we|I.ve been)\b',
    re.IGNORECASE,
)

# First person ACTION — "I updated", "I implemented" (AI pattern)
FIRST_PERSON_ACT_RE = re.compile(
    r'\b(?:I (?:updated|implemented|added|removed|changed|fixed|refactored|'
    r'created|modified|replaced|introduced|migrated|converted|ensured))\b',
    re.IGNORECASE,
)

# @mentions of people (not bots, npm scoped packages, or doc-tag keywords)
AT_MENTION_RE = re.compile(r'@[a-zA-Z][a-zA-Z0-9_-]{1,38}')
# Matches followed by '/' are npm scoped packages, not people
AT_SCOPED_PKG_RE = re.compile(r'@[a-zA-Z][a-zA-Z0-9_-]{1,38}/')
BOT_MENTION_FILTER = re.compile(
    r'bot|copilot|coderabbit|renovate|dependabot|biomejs|cloudflare|types',
    re.IGNORECASE,
)
# JSDoc/JavaDoc keywords that look like @mentions but aren't people
DOC_TAG_KEYWORDS = {
    '@param', '@returns', '@return', '@override', '@deprecated',
    '@throws', '@type', '@typedef', '@property', '@interface',
}

# ═══════════════════════════════════════════════════════════════════════
# 4. ORGANIZATIONAL CONTEXT — only a human would know this
# ═══════════════════════════════════════════════════════════════════════

# References to prior events/history
HISTORY_RE = re.compile(
    r'(?:we tried|previously|used to|broke (?:in|on) (?:prod|staging|ci)|'
    r'was wrong|the issue (?:is|was)|root cause|after investigating|'
    r'after debugging|regression from|this (?:broke|regressed)|'
    r'left over from|remnant of|legacy|historically|'
    r'back when we|originally|in the old)',
    re.IGNORECASE,
)

# References to people, teams, discussions
PEOPLE_CONTEXT_RE = re.compile(
    r'(?:per (?:discussion|slack|conversation|call|meeting|sync|standup)|'
    r'talked to|discussed with|agreed with|as .+ (?:suggested|mentioned|noted|pointed out)|'
    r'cc @|ping @|thanks to @|h/t @|credit to|'
    r'the .+ team|marketing|legal|compliance|design|product|PM |'
    r'stakeholder|customer (?:asked|reported|wants|needs))',
    re.IGNORECASE,
)

# References to external context (outside the codebase)
EXTERNAL_CONTEXT_RE = re.compile(
    r'(?:legal (?:flagged|requires|requirement)|compliance|'
    r'API partner|vendor|third.party|SLA|contract|deadline|'
    r'Q[1-4] |sprint|release (?:freeze|branch|cycle)|'
    r'the (?:client|customer|user) (?:reported|asked|wants|needs)|'
    r'incident|outage|postmortem|on.?call|pager|alert|'
    r'deprecating|sunset|EOL|end of life)',
    re.IGNORECASE,
)

# Incident references
INCIDENT_RE = re.compile(
    r'(?:incident|outage|postmortem|post.mortem|broke in prod|'
    r'production (?:issue|bug|failure|error)|hotfix|'
    r'emergency|urgent|critical (?:bug|issue|fix)|'
    r'customers? (?:affected|impacted|reporting)|'
    r'P[012] |SEV.?[012]|on.?call)',
    re.IGNORECASE,
)

# ═══════════════════════════════════════════════════════════════════════
# 5. REASONING QUALITY — things AI is bad at
# ═══════════════════════════════════════════════════════════════════════

# Negation depth — what must NOT happen (AI defaults to positive assertions, 9.5% accuracy on null effects)
NEGATION_RE = re.compile(
    r'(?:must not|should not|will not|cannot|shall not|'
    r'do not (?:change|modify|touch|remove|delete|update)|'
    r'not (?:doing|including|changing|addressing)|'
    r'out of scope|excluded|non.?goal|'
    r'won.t (?:fix|do|include|handle|support)|'
    r'explicitly (?:not|excluded|omitted)|'
    r'this does NOT|avoid (?:changing|modifying|touching))',
    re.IGNORECASE,
)

# Causal chains — WHY a constraint exists, not just WHAT
# "because our payment provider throttles at 100 req/s" vs "rate limiting required"
CAUSAL_RE = re.compile(
    r'(?:because (?:of |the |our |it |this |when )|'
    r'the reason (?:is|being|for)|since (?:the |our |we )|'
    r'due to (?:the |a |an )|this (?:is because|happens because|causes)|'
    r'which (?:causes|leads to|results in|means|prevents)|'
    r'otherwise|if we don.t|without this)',
    re.IGNORECASE,
)

# Edge case specificity — concrete values vs generic
# "Cart with 0 items after last item removed during checkout race condition" vs "empty cart"
SPECIFIC_EDGE_RE = re.compile(
    r'(?:when .+ (?:is|are|has|have) (?:null|nil|zero|empty|0|negative|missing|undefined)|'
    r'race condition|concurrent|timeout after \d|'
    r'if .+ (?:fails|throws|returns) .+ (?:while|during|after)|'
    r'edge case.? (?:where|when|if)|'
    r'corner case|boundary|overflow|underflow|truncat)',
    re.IGNORECASE,
)

# Generic edge cases (AI pattern — lists obvious cases)
GENERIC_EDGE_RE = re.compile(
    r'(?:handle (?:edge cases|errors|failures|exceptions)|'
    r'error handling|input validation|'
    r'empty (?:input|string|list|array|response)|null (?:check|handling)|'
    r'graceful(?:ly)?)',
    re.IGNORECASE,
)

# Contradiction/tradeoff awareness — AI rarely surfaces tradeoffs unprompted
TRADEOFF_RE = re.compile(
    r'(?:trade.?off|chose .+ (?:because|over|instead)|'
    r'at the cost of|downside|drawback|'
    r'pro(?:s)? and con(?:s)?|alternative(?:ly|s)?|'
    r'option [AB12]|considered (?:but|however)|'
    r'sacrific|compromise|tension between|'
    r'this means we (?:can.t|won.t|lose)|'
    r'the tricky (?:part|thing|bit) is)',
    re.IGNORECASE,
)

# Domain grounding — tied to specific system details vs generic
DOMAIN_GROUND_RE = re.compile(
    r'(?:src/|lib/|pkg/|cmd/|internal/|\.(?:ts|py|go|rs|java|rb|zig)\b|'
    r'the .+ (?:endpoint|table|column|field|service|module|class|function)|'
    r'in (?:production|staging|CI)|'
    r'our .+ (?:service|API|database|queue|cache)|'
    r'(?:POST|GET|PUT|DELETE|PATCH) /[a-z]|'
    r'\d+ (?:ms|sec|min|req/s|MB|GB|%|users|rows))',
    re.IGNORECASE,
)

# ═══════════════════════════════════════════════════════════════════════
# 6. TEMPLATE/SLOP — performative structure without substance
# ═══════════════════════════════════════════════════════════════════════

# Template phrases (changelog-style, AI pattern)
TEMPLATE_RE = re.compile(
    r'(?:This (?:PR|change|commit) (?:introduces|implements|adds|updates|improves|'
    r'enhances|addresses|resolves|fixes)|'
    r'Key (?:changes|improvements|features) include|'
    r'The following changes|changes (?:include|are as follows)|'
    r'The most important changes (?:are|include))',
    re.IGNORECASE,
)

# Slop terms (AI filler words)
SLOP_RE = re.compile(
    r'\b(?:comprehensive|robust|seamless|leverage|streamline|holistic|'
    r'in order to|ensure that|efficiently|straightforward|delve|'
    r'enhance|utilize|facilitate)\b',
    re.IGNORECASE,
)

# Section header only (test plan / risk section exists but is just a header or checkboxes)
EMPTY_SECTION_RE = re.compile(
    r'^##\s*(?:Test [Pp]lan|Risk|Breaking [Cc]hanges?)\s*$',
    re.MULTILINE,
)

# PR references
ISSUE_REF_RE = re.compile(r'(?:[Cc]loses?|[Ff]ixes?|[Rr]esolves?) #\d{3,}', re.IGNORECASE)
ANY_ISSUE_REF_RE = re.compile(r'#\d{3,}')

# ═══════════════════════════════════════════════════════════════════════
# 7. TEXT STATISTICS
# ═══════════════════════════════════════════════════════════════════════


def _sentence_lengths(text: str) -> list[int]:
    sentences = re.split(r'[.!?]\s+', text)
    return [len(s.split()) for s in sentences if len(s.split()) >= 3]


def _type_token_ratio(text: str) -> float:
    words = re.findall(r'\b[a-zA-Z]{2,}\b', text.lower())
    if not words:
        return 0.0
    return len(set(words)) / len(words)


def _count_syllables(word: str) -> int:
    """Approximate syllable count for readability metrics."""
    word = word.lower().rstrip('e')
    vowels = 'aeiouy'
    count = 0
    prev_vowel = False
    for c in word:
        is_vowel = c in vowels
        if is_vowel and not prev_vowel:
            count += 1
        prev_vowel = is_vowel
    return max(1, count)


# ═══════════════════════════════════════════════════════════════════════
# COMPUTE
# ═══════════════════════════════════════════════════════════════════════


def compute_features(pr: dict) -> dict:
    body = pr.get('body', '') or ''
    author = pr.get('author', '')
    title = pr.get('title', '')

    # 1. Author classification
    author_lower = author.lower()
    is_bot_author = (
        author.startswith('app/')
        or author_lower in BOT_AUTHORS
        or 'bot' in author_lower
        or any(pat in author_lower for pat in BOT_AUTHORS)
    )

    # 2. AI self-tag (regex patterns + structured AI Disclosure sections)
    ai_tagged = bool(AI_TAG_RE.search(body))
    ai_disclosure = _check_ai_disclosure(body)
    if ai_disclosure is True:
        ai_tagged = True  # Disclosure overrides: developer explicitly said AI was used

    # 3. Humanness
    typos = len(TYPO_RE.findall(body))
    casual = len(CASUAL_RE.findall(body))
    questions = len(QUESTION_RE.findall(body))
    fp_experience = len(FIRST_PERSON_EXP_RE.findall(body))
    fp_action = len(FIRST_PERSON_ACT_RE.findall(body))
    # Filter out npm scoped packages (@types/node), bot mentions, and doc-tag keywords
    scoped_pkgs = set(m.rstrip('/') for m in AT_SCOPED_PKG_RE.findall(body))
    mentions = AT_MENTION_RE.findall(body)
    human_mentions = len([m for m in mentions
                          if not BOT_MENTION_FILTER.search(m)
                          and m not in scoped_pkgs
                          and m.lower() not in DOC_TAG_KEYWORDS])

    # 4. Organizational context
    history = len(HISTORY_RE.findall(body))
    people_context = len(PEOPLE_CONTEXT_RE.findall(body))
    external_context = len(EXTERNAL_CONTEXT_RE.findall(body))
    incidents = len(INCIDENT_RE.findall(body))
    has_org_context = 1 if (history + people_context + external_context + incidents) > 0 else 0

    # 5. Reasoning quality
    negations = len(NEGATION_RE.findall(body))
    causal_chains = len(CAUSAL_RE.findall(body))
    specific_edges = len(SPECIFIC_EDGE_RE.findall(body))
    generic_edges = len(GENERIC_EDGE_RE.findall(body))
    tradeoffs = len(TRADEOFF_RE.findall(body))
    domain_grounding = len(DOMAIN_GROUND_RE.findall(body))

    # 6. Template/slop
    templates = len(TEMPLATE_RE.findall(body))
    slop = len(SLOP_RE.findall(body))
    empty_sections = len(EMPTY_SECTION_RE.findall(body))
    issue_refs = len(ISSUE_REF_RE.findall(body))
    any_issue_refs = len(ANY_ISSUE_REF_RE.findall(body))

    # 7. Text statistics
    body_len = len(body)
    word_count = len(body.split())
    sent_lengths = _sentence_lengths(body)
    ttr = _type_token_ratio(body)

    if sent_lengths:
        sent_len_mean = sum(sent_lengths) / len(sent_lengths)
        sent_len_std = (sum((x - sent_len_mean) ** 2 for x in sent_lengths) / len(sent_lengths)) ** 0.5
    else:
        sent_len_mean = 0
        sent_len_std = 0

    words = re.findall(r'\b[a-zA-Z]+\b', body)
    avg_word_len = sum(len(w) for w in words) / len(words) if words else 0

    # 8. StyloAI-aligned features (from StyloAI, arXiv:2405.10129)
    words_lower = [w.lower() for w in words]
    unique_word_count = len(set(words_lower))
    # Hapax legomena: words appearing exactly once
    from collections import Counter as _Counter
    word_freqs = _Counter(words_lower)
    hapax_rate = sum(1 for c in word_freqs.values() if c == 1) / len(words_lower) if words_lower else 0

    sentence_count = len(sent_lengths)
    punctuation_count = sum(1 for c in body if c in '.,;:!?-()[]{}"\'/\\')
    exclamation_count = body.count('!')

    # Stopwords (lightweight, no nltk needed)
    STOPWORDS = {'the','a','an','is','are','was','were','be','been','being','have','has','had',
                 'do','does','did','will','would','could','should','may','might','shall','can',
                 'to','of','in','for','on','with','at','by','from','as','into','through','during',
                 'before','after','above','below','between','out','off','over','under','again',
                 'further','then','once','that','this','these','those','it','its','and','but','or',
                 'nor','not','no','so','if','than','too','very','just','about','up','down','here',
                 'there','when','where','why','how','all','each','every','both','few','more','most',
                 'other','some','such','only','own','same','also','back','even','still','new'}
    stop_word_count = sum(1 for w in words_lower if w in STOPWORDS)

    # Direct address (you/your)
    direct_address_count = sum(1 for w in words_lower if w in ('you', 'your', 'yours', 'yourself'))

    # Bigram/trigram uniqueness
    bigrams = list(zip(words_lower, words_lower[1:])) if len(words_lower) > 1 else []
    bigram_uniqueness = len(set(bigrams)) / len(bigrams) if bigrams else 0
    trigrams = list(zip(words_lower, words_lower[1:], words_lower[2:])) if len(words_lower) > 2 else []
    trigram_uniqueness = len(set(trigrams)) / len(trigrams) if trigrams else 0

    # Readability: Flesch Reading Ease
    syllable_count = sum(_count_syllables(w) for w in words)
    if sentence_count > 0 and len(words) > 0:
        flesch = 206.835 - 1.015 * (len(words) / sentence_count) - 84.6 * (syllable_count / len(words))
        # Gunning Fog: 0.4 * (words/sentences + 100 * complex_words/words)
        complex_words = sum(1 for w in words if _count_syllables(w) >= 3)
        gunning_fog = 0.4 * (len(words) / sentence_count + 100 * complex_words / len(words))
    else:
        flesch = 0
        gunning_fog = 0

    # VADER sentiment (if available)
    vader_compound = 0
    try:
        from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer as _SIA
        _vader = _SIA()
        vader_compound = _vader.polarity_scores(body[:5000])['compound']
    except ImportError:
        pass

    # Composites — intentionally unweighted (simple presence detection).
    # Each signal is a count; summing gives a broad "any humanness present"
    # indicator rather than a weighted prediction score. Weighting would
    # require a calibration dataset we don't yet have.
    human_signals = typos + casual + questions
    org_context_signals = history + people_context + external_context + incidents
    reasoning_signals = negations + causal_chains + specific_edges + tradeoffs
    anti_signals = templates + slop + fp_action + empty_sections

    # Edge case ratio: specific / (specific + generic). High = real thinking, low = generic
    edge_ratio = specific_edges / (specific_edges + generic_edges) if (specific_edges + generic_edges) > 0 else -1

    # ── Pre-PR conversation proxies ──────────────────────────────────
    from datetime import datetime as _dt

    created_at = pr.get('created_at')
    merged_at = pr.get('merged_at')
    reviews = pr.get('reviews', []) or []

    # Time PR was open (created → merged) in hours
    pr_open_hours = 0
    if created_at and merged_at:
        try:
            c = _dt.fromisoformat(str(created_at).replace('Z', '+00:00'))
            m = _dt.fromisoformat(str(merged_at).replace('Z', '+00:00'))
            pr_open_hours = max(0, (m - c).total_seconds() / 3600)
        except Exception:
            pass

    # Time to first human review (created → first non-bot review)
    time_to_first_review_hours = 0
    human_reviews = [r for r in reviews if not r.get('is_bot', False)]
    if created_at and human_reviews:
        try:
            c = _dt.fromisoformat(str(created_at).replace('Z', '+00:00'))
            review_times = []
            for rev in human_reviews:
                sub = rev.get('submitted_at')
                if sub:
                    review_times.append(_dt.fromisoformat(str(sub).replace('Z', '+00:00')))
            if review_times:
                first = min(review_times)
                time_to_first_review_hours = max(0, (first - c).total_seconds() / 3600)
        except Exception:
            pass

    # Number of unique human reviewers
    unique_human_reviewers = len(set(
        r['reviewer'] for r in human_reviews if r.get('reviewer')
    ))

    # Number of review rounds (count of distinct review submissions)
    review_count = len(human_reviews)

    # Did the author respond to review? (author has review submissions on own PR)
    author_self_reviews = len([
        r for r in reviews
        if r.get('reviewer') == author and r.get('state') == 'commented'
    ])

    # Bot review count
    bot_review_count = len([r for r in reviews if r.get('is_bot', False)])

    return {
        'repo': pr.get('repo', ''),
        'pr_number': pr['pr_number'],
        'author': author,

        # Classification
        'is_bot_author': is_bot_author,
        'ai_tagged': ai_tagged,

        # Humanness
        'typos': typos,
        'casual': casual,
        'questions': questions,
        'fp_experience': fp_experience,
        'fp_action': fp_action,
        'human_mentions': human_mentions,

        # Organizational context
        'history': history,
        'people_context': people_context,
        'external_context': external_context,
        'incidents': incidents,
        'has_org_context': has_org_context,

        # Reasoning
        'negations': negations,
        'causal_chains': causal_chains,
        'specific_edges': specific_edges,
        'generic_edges': generic_edges,
        'edge_ratio': round(edge_ratio, 2) if edge_ratio >= 0 else '',
        'tradeoffs': tradeoffs,
        'domain_grounding': domain_grounding,

        # Template/slop
        'templates': templates,
        'slop': slop,
        'empty_sections': empty_sections,
        'issue_refs': issue_refs,
        'any_issue_refs': any_issue_refs,

        # Text stats
        'body_len': body_len,
        'word_count': word_count,
        'sent_len_mean': round(sent_len_mean, 1),
        'sent_len_std': round(sent_len_std, 1),
        'type_token_ratio': round(ttr, 3),
        'avg_word_len': round(avg_word_len, 1),

        # StyloAI-aligned features (arXiv:2405.10129)
        'unique_word_count': unique_word_count,
        'hapax_rate': round(hapax_rate, 3),
        'sentence_count': sentence_count,
        'punctuation_count': punctuation_count,
        'exclamation_count': exclamation_count,
        'stop_word_count': stop_word_count,
        'direct_address_count': direct_address_count,
        'bigram_uniqueness': round(bigram_uniqueness, 3),
        'trigram_uniqueness': round(trigram_uniqueness, 3),
        'flesch_reading_ease': round(flesch, 1),
        'gunning_fog': round(gunning_fog, 1),
        'vader_compound': round(vader_compound, 3),

        # Pre-PR conversation proxies
        'pr_open_hours': round(pr_open_hours, 1),
        'time_to_first_review_hours': round(time_to_first_review_hours, 1),
        'unique_human_reviewers': unique_human_reviewers,
        'review_count': review_count,
        'author_self_reviews': author_self_reviews,
        'bot_review_count': bot_review_count,

        # Composites
        'human_signals': human_signals,
        'org_context_signals': org_context_signals,
        'reasoning_signals': reasoning_signals,
        'anti_signals': anti_signals,

        # Perplexity (filled by _compute_perplexity pass, 0 = not computed)
        'perplexity': 0,
    }


def _compute_perplexity_batch(features: list[dict], prs_by_key: dict) -> None:
    """Compute GPT-2 perplexity for each PR body. Modifies features in place."""
    try:
        import torch
        from transformers import GPT2LMHeadModel, GPT2Tokenizer
        import math
    except ImportError:
        print("  Skipping perplexity (install: pip install transformers torch)")
        return

    print("  Loading GPT-2 for perplexity...", flush=True)
    tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
    model = GPT2LMHeadModel.from_pretrained("gpt2")
    model.eval()

    scored = 0
    for i, feat in enumerate(features):
        key = (feat['repo'], feat['pr_number'])
        pr = prs_by_key.get(key)
        if not pr:
            continue
        body = (pr.get('body') or '')[:2000]
        if len(body) < 50:
            continue

        tokens = tokenizer.encode(body, return_tensors="pt", truncation=True, max_length=512)
        if tokens.shape[1] < 2:
            continue

        try:
            with torch.no_grad():
                outputs = model(tokens, labels=tokens)
                loss_val = outputs.loss.item()
                if math.isfinite(loss_val) and loss_val < 700:
                    feat['perplexity'] = round(math.exp(loss_val), 1)
                else:
                    feat['perplexity'] = 0  # overflow guard
        except Exception:
            continue  # skip this PR, don't abort the batch

        scored += 1
        if scored % 500 == 0:
            print(f"    [{scored} PRs scored for perplexity]", flush=True)

    print(f"  Perplexity computed for {scored} PRs", flush=True)


def main():
    all_features = []
    prs_by_key = {}

    for prs_path in sorted(DATA_DIR.glob('prs-*.json')):
        prs = json.loads(prs_path.read_text())
        for pr in prs:
            all_features.append(compute_features(pr))
            prs_by_key[(pr.get('repo', ''), pr['pr_number'])] = pr

    # Compute perplexity (second pass, requires GPU-optional model)
    _compute_perplexity_batch(all_features, prs_by_key)

    # Write CSV (atomic via temp file)
    out_path = DATA_DIR / 'pr-features.csv'
    fieldnames = list(all_features[0].keys())
    tmp_path = out_path.with_suffix('.csv.tmp')
    with open(tmp_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(all_features)
    tmp_path.replace(out_path)

    print(f"Wrote {len(all_features)} rows to {out_path}")
    print(f"Columns: {len(fieldnames)}")

    # Validation against AI-tagged ground truth
    tagged = [r for r in all_features if r['ai_tagged']]
    humans = [r for r in all_features if not r['ai_tagged'] and not r['is_bot_author']]

    print(f"\n{'='*70}")
    print(f"VALIDATION: AI-tagged ({len(tagged)}) vs Human ({len(humans)})")
    print(f"{'='*70}\n")

    features_to_check = [
        # Humanness
        ('typos', 'HUMAN'), ('casual', 'HUMAN'), ('questions', 'HUMAN'),
        ('fp_experience', '???'), ('fp_action', '???'), ('human_mentions', 'HUMAN'),
        # Org context
        ('history', '???'), ('people_context', 'HUMAN'), ('external_context', 'HUMAN'),
        ('incidents', 'HUMAN'), ('has_org_context', 'HUMAN'),
        # Reasoning
        ('negations', '???'), ('causal_chains', '???'),
        ('specific_edges', '???'), ('generic_edges', '???'),
        ('tradeoffs', '???'), ('domain_grounding', '???'),
        # Anti-signals
        ('templates', 'AI'), ('slop', 'AI'), ('empty_sections', 'AI'),
        # Text stats
        ('body_len', '???'), ('type_token_ratio', 'HUMAN'),
        ('avg_word_len', 'AI'), ('sent_len_std', '???'),
        # Composites
        ('human_signals', 'HUMAN'), ('org_context_signals', '???'),
        ('reasoning_signals', '???'), ('anti_signals', 'AI'),
    ]

    print(f"{'Feature':25s} {'AI avg':>8s} {'Human avg':>10s} {'Winner':>8s} {'Ratio':>7s} {'Expected':>10s} {'Match':>6s}")
    print('-' * 80)
    for feat, expected in features_to_check:
        ai_vals = [r[feat] for r in tagged if r[feat] != '']
        hu_vals = [r[feat] for r in humans if r[feat] != '']
        ai_avg = sum(float(v) for v in ai_vals) / len(ai_vals) if ai_vals else 0
        hu_avg = sum(float(v) for v in hu_vals) / len(hu_vals) if hu_vals else 0

        if ai_avg + hu_avg == 0:
            continue

        winner = 'HUMAN' if hu_avg > ai_avg else 'AI' if ai_avg > hu_avg else 'TIE'
        ratio = hu_avg / ai_avg if ai_avg > 0 else float('inf')
        match = 'YES' if expected == '???' or winner == expected else 'NO'

        ratio_str = f'{ratio:.1f}x' if ratio != float('inf') else 'inf'
        print(f"{feat:25s} {ai_avg:8.3f} {hu_avg:10.3f} {winner:>8s} {ratio_str:>7s} {expected:>10s} {match:>6s}")


if __name__ == '__main__':
    main()
