#!/usr/bin/env python3
"""
Search all PR data for references to SDD tools (Spec Kit, Kiro).

Checks PR titles, descriptions, and file paths for tool-specific patterns.
Used to verify whether any PRs in the study dataset were generated by
or reference SDD tool workflows.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"

patterns = [".specify", ".speckit", ".kiro", "spec-kit", "speckit", "kiro"]

total_prs = 0
matches = {p: [] for p in patterns}

for f in sorted(DATA_DIR.glob("prs-*.json")):
    with open(f) as fh:
        prs = json.load(fh)
    repo = f.stem.replace("prs-", "").replace("-", "/", 1)

    for pr in prs:
        total_prs += 1
        body = (pr.get("body") or "").lower()
        title = (pr.get("title") or "").lower()

        files_raw = pr.get("files", [])
        if isinstance(files_raw, list):
            file_paths = []
            for item in files_raw:
                if isinstance(item, dict):
                    file_paths.append(item.get("path", "").lower())
                elif isinstance(item, str):
                    file_paths.append(item.lower())
            files = " ".join(file_paths)
        else:
            files = ""

        search_text = body + " " + title + " " + files

        for pattern in patterns:
            if pattern in search_text:
                pr_num = pr.get("number", "?")
                idx = search_text.find(pattern)
                snippet = search_text[max(0, idx - 40):idx + len(pattern) + 40]
                snippet = snippet.replace("\n", " ").strip()
                matches[pattern].append((f"{repo}#{pr_num}", snippet))

print(f"Total PRs scanned: {total_prs:,}")
print()
for pattern, hits in matches.items():
    print(f'"{pattern}": {len(hits)} matches')
    for pr_ref, snippet in hits[:20]:
        print(f"  {pr_ref}: ...{snippet}...")
    if len(hits) > 20:
        print(f"  ... and {len(hits) - 20} more")
    print()
